### PR TITLE
fix(web): fix sidebar design mismatch

### LINKED ISSUE #96: Design mismatch in Sidebar component
**1. Overflow of content between responsive states**

- Set browser width to mobile size
- Close the side bar
- Set browser width to desktop size
- Close the side bar

Expected: 
Image

Got:

Image

**2. Help button should be at the bottom of the screen in mobile screens**

Image

### PR DESCRIPTION
**Pull request by yiningsoong**
closes #96 

## 🚀 Summary

Fix issues raised in #96 

## ✏️ Changes

1. Add `flex` to mobile sidebar for 'Help' to stick to the bottom
2. Stricter checks for expanded sidebar to ensure labels are not visible, when moving between responsive states 
3. ~~Add `isExpanded` to `SidebarProvider`~~

### CODE REVIEW

File: web/components/Sidebar/SidebarItem.tsx [hunk 1]
```diff
@@ -100,7 +99,7 @@ const SidebarItem: React.FC<SidebarItemProps> = ({
       <Icon className="flex h-4 w-4 shrink-0 text-slate-11" />
 
       <AnimatePresence initial={false}>
-        {(isOpen || isMobileOpen) && (
+        {isExpanded && (
```
Comment (YimingIsCOLD) [inline web/components/Sidebar/SidebarItem.tsx:104]: Instead of introducing `isExpanded`, can we fix it with `isOpen || (isMobile && isMobileOpen)`?

File: web/components/Sidebar/SidebarItem.tsx [hunk 2]
```diff
@@ -168,6 +167,7 @@ const SidebarItem: React.FC<SidebarItemProps> = ({
   }
 
   const { onPointerMove, ...buttonProps } = props;
+
```
Comment (YimingIsCOLD) [inline web/components/Sidebar/SidebarItem.tsx:174]: If we add this newline, should the above destructuring in `href` and `to` branch have the newline too?

**Review by YimingIsCOLD — APPROVED** [review]

**Review by kellylimmm — APPROVED** [review]
